name: Deploy app to Github Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .Net Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0
      
      - name: Publish the project
        run: dotnet publish Lyrica/Lyrica/Lyrica.csproj -c Release -o release --nologo
        
      
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
      
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html
      
      - name: Commit wwwroot to Github Page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GTHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-page
          FOLDER: release/wwwroot
